version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: reporter
      POSTGRES_PASSWORD: reporter_pass
      POSTGRES_DB: public_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reporter -d public_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      POSTGRES_DB: public_service_db
      POSTGRES_USER: reporter
      POSTGRES_PASSWORD: reporter_pass
      DB_HOST: db
      DB_PORT: "5432"
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:8080"

volumes:
  postgres_data:
