# Generated by Django 4.2 on 2026-06-21 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-likes', '-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
