# Generated by Django 6.0.5 on 2026-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reports',
        ),
    ]
